# taken from http://www.aemo.com.au/About-the-Industry/Registration/Current-Registration-and-Exemption-lists
insert into stationdata values('BAPS',12.85,'Hydro','Water','Renewable','Hydro - Gravity','AGL Hydro Partnership','Banimboola Power Station')
insert into stationdata values('BAPS',,'Hydro','Water','Renewable','Hydro - Gravity','AGL Hydro Partnership','Banimboola Power Station');
insert into stationdata values('MCKAY1',300,'Hydro','Water','Renewable','Hydro - Gravity','AGL Hydro Partnership','Bogong / Mckay Power Station');
insert into stationdata values('MCKAY1',,'Hydro','Water','Renewable','Hydro - Gravity','AGL Hydro Partnership','Bogong / Mckay Power Station');
insert into stationdata values('BROKENH1',53.76,'Solar','Solar','Renewable','Photovoltaic Flat Panel','AGL Hydro Partnership','Broken Hill Solar Plant');
insert into stationdata values('BDONGHYD',19,'Hydro','Water','Renewable','Hydro - Gravity','AGL Hydro Partnership','Burrendong Hydro Power Station');
insert into stationdata values('-',30,'Hydro','Water','Renewable','Hydro - Gravity','AGL Hydro Partnership','Clover Power Station');
insert into stationdata values('COPTNHYD',24,'Hydro','Water','Renewable','Hydro - Gravity','AGL Hydro Partnership','Copeton Hydro Power Station');
insert into stationdata values('DARTM1',150,'Hydro','Water','Renewable','Hydro - Gravity','AGL Hydro Partnership','Dartmouth Power Station');
insert into stationdata values('EILDON1',60,'Hydro','Water','Renewable','Hydro - Gravity','AGL Hydro Partnership','Eildon Power Station');
insert into stationdata values('EILDON2',60,'Hydro','Water','Renewable','Hydro - Gravity','AGL Hydro Partnership','Eildon Power Station');
insert into stationdata values('EILDON2',,'Hydro','Water','Renewable','Hydro - Gravity','AGL Hydro Partnership','Eildon Power Station');
insert into stationdata values('GLBWNHYD',5.8,'Hydro','Water','Renewable','Hydro - Gravity','AGL Hydro Partnership','Glenbawn Hydro Power Station');
insert into stationdata values('HALLWF1',94.5,'Wind','Wind','Renewable','Wind - Onshore','AGL Hydro Partnership','Hallett 1 Wind Farm');
insert into stationdata values('HALLWF2',71.4,'Wind','Wind','Renewable','Wind - Onshore','AGL Hydro Partnership','Hallett 2 Wind Farm');
insert into stationdata values('ICSM',25,'Renewable/ Biomass / Waste','Bagasse','Combustion','Steam Sub-Critical','AGL Hydro Partnership','ISIS Central Sugar Mill Co-generation Plant');
insert into stationdata values('KINCUM1',1.064,'Landfill, Biogas','Landfill, Biogas','Renewable','Landfill, Biogas','AGL Hydro Partnership','Kincumber Landfill Site');
insert into stationdata values('MACARTH1',420,'Wind','Wind','Renewable','Wind - Onshore','AGL Hydro Partnership','Macarthur Wind Farm');
insert into stationdata values('MORANBAH',12.56,'Fossil','Coal Seam Methane','Combustion','Compression Reciprocating Engine','AGL Hydro Partnership','Moranbah Generation Project');
insert into stationdata values('NBHWF1',132.3,'Wind','Wind','Renewable','Wind - Onshore','AGL Hydro Partnership','North Brown Hill Wind Farm');
insert into stationdata values('NYNGAN1',102,'Solar','Solar PV','Renewable','Photovoltaic Flat Panel','AGL Hydro Partnership','Nyngan Solar Plant');
insert into stationdata values('OAKLAND1',67,'Wind','Wind','Renewable','Wind - Onshore','AGL Hydro Partnership','Oaklands Hill Wind Farm');
insert into stationdata values('PINDARI',6.7,'Hydro','Water','Renewable','Hydro - Gravity','AGL Hydro Partnership','Pindari Hydro Power Station');
insert into stationdata values('EDLRGNRD',2,'Renewable/ Biomass / Waste','Bagasse','Combustion','Steam Sub-Critical','AGL Hydro Partnership','Roghan Road LFG Power Plant');
insert into stationdata values('-',13.55,'Hydro','Water','Renewable','Hydro - Gravity','AGL Hydro Partnership','Rubicon Mountain Streams Station');
insert into stationdata values('AGLSOM',160,'Fossil','Natural Gas','Combustion','Open Cycle Gas turbines (OCGT)','AGL Hydro Partnership','Somerton Power Station');
insert into stationdata values('SUNCOAST',1.5,'Renewable/ Biomass / Waste','Macadamia Nut Shells','Combustion','Steam Sub-Critical','AGL Hydro Partnership','Suncoast Gold Macadamias');
insert into stationdata values('BLUFF1',52.5,'Wind','Wind','Renewable','Wind - Onshore','AGL Hydro Partnership','The Bluff Wind Farm');
insert into stationdata values('YABULU',160,'Fossil','Natural Gas','Combustion','Open Cycle Gas turbines (OCGT)','AGL Hydro Partnership','Townsville Gas Turbine');
insert into stationdata values('YABULU2',82,'Fossil','Natural Gas','Combustion','Open Cycle Gas turbines (OCGT)','AGL Hydro Partnership','Townsville Gas Turbine');
insert into stationdata values('WPWF',90.75,'Wind','Wind','Renewable','Wind - Onshore','AGL Hydro Partnership','Wattle Point Wind Farm');
insert into stationdata values('WKIEWA1',31,'Hydro','Water','Renewable','Hydro - Gravity','AGL Hydro Partnership','West Kiewa Power Station');
insert into stationdata values('WKIEWA2',31,'Hydro','Water','Renewable','Hydro - Gravity','AGL Hydro Partnership','West Kiewa Power Station');
insert into stationdata values('AGLNOW1',1,'Renewable/ Biomass / Waste','Landfill Methane / Landfill Gas','Combustion','Compression Reciprocating Engine','AGL Hydro Partnership','West Nowra Landfill Gas Power Generation Facility');
insert into stationdata values('WOYWOY1',1.064,'Landfill / Biogas','Landfill / Biogas','Combustion','Compression Reciprocating Engine','AGL Hydro Partnership','Woy Woy Landfill Site');
insert into stationdata values('-',9,'Hydro','Water','Renewable','Hydro - Gravity','AGL Hydro Partnership','Yarrawonga Hydro Power Station');
insert into stationdata values('LYA1',560,'Fossil','Brown Coal','Combustion','Steam Sub-Critical','AGL Loy Yang Marketing Pty Ltd','Loy Yang A Power Station');
insert into stationdata values('LYA2',530,'Fossil','Brown Coal','Combustion','Steam Sub-Critical','AGL Loy Yang Marketing Pty Ltd','Loy Yang A Power Station');
insert into stationdata values('LYA3',560,'Fossil','Brown Coal','Combustion','Steam Sub-Critical','AGL Loy Yang Marketing Pty Ltd','Loy Yang A Power Station');
insert into stationdata values('LYA4',560,'Fossil','Brown Coal','Combustion','Steam Sub-Critical','AGL Loy Yang Marketing Pty Ltd','Loy Yang A Power Station');
insert into stationdata values('BW01',660,'Fossil','Black Coal','Combustion','Steam Sub-Critical','AGL Macquarie Pty Limited','Bayswater Power Station');
insert into stationdata values('BW02',660,'Fossil','Black Coal','Combustion','Steam Sub-Critical','AGL Macquarie Pty Limited','Bayswater Power Station');
insert into stationdata values('BW03',660,'Fossil','Black Coal','Combustion','Steam Sub-Critical','AGL Macquarie Pty Limited','Bayswater Power Station');
insert into stationdata values('BW04',660,'Fossil','Black Coal','Combustion','Steam Sub-Critical','AGL Macquarie Pty Limited','Bayswater Power Station');
insert into stationdata values('HVGTS',50,'Fossil','Kerosene','Combustion','Open Cycle Gas turbines (OCGT)','AGL Macquarie Pty Limited','Hunter Valley Gas Turbine ');
insert into stationdata values('LD01',500,'Fossil','Black Coal','Combustion','Steam Sub-Critical','AGL Macquarie Pty Limited','Liddell Power Station');
insert into stationdata values('LD02',500,'Fossil','Black Coal','Combustion','Steam Sub-Critical','AGL Macquarie Pty Limited','Liddell Power Station');
insert into stationdata values('LD03',500,'Fossil','Black Coal','Combustion','Steam Sub-Critical','AGL Macquarie Pty Limited','Liddell Power Station');
insert into stationdata values('LD04',500,'Fossil','Black Coal','Combustion','Steam Sub-Critical','AGL Macquarie Pty Limited','Liddell Power Station');
insert into stationdata values('TORRA1',120,'Fossil','Natural Gas / Fuel Oil','Combustion','Steam Sub-Critical','AGL SA Generation Pty Limited ','Torrens Island Power Station "A"');
insert into stationdata values('TORRA2',120,'Fossil','Natural Gas / Fuel Oil','Combustion','Steam Sub-Critical','AGL SA Generation Pty Limited ','Torrens Island Power Station "A"');
insert into stationdata values('TORRA3',120,'Fossil','Natural Gas / Fuel Oil','Combustion','Steam Sub-Critical','AGL SA Generation Pty Limited ','Torrens Island Power Station "A"');
insert into stationdata values('TORRA4',120,'Fossil','Natural Gas / Fuel Oil','Combustion','Steam Sub-Critical','AGL SA Generation Pty Limited ','Torrens Island Power Station "A"');
insert into stationdata values('TORRB1',200,'Fossil','Natural Gas / Fuel Oil','Combustion','Steam Sub-Critical','AGL SA Generation Pty Limited ','Torrens Island Power Station "B"');
insert into stationdata values('TORRB2',200,'Fossil','Natural Gas / Fuel Oil','Combustion','Steam Sub-Critical','AGL SA Generation Pty Limited ','Torrens Island Power Station "B"');
insert into stationdata values('TORRB3',200,'Fossil','Natural Gas / Fuel Oil','Combustion','Steam Sub-Critical','AGL SA Generation Pty Limited ','Torrens Island Power Station "B"');
insert into stationdata values('TORRB4',200,'Fossil','Natural Gas / Fuel Oil','Combustion','Steam Sub-Critical','AGL SA Generation Pty Limited ','Torrens Island Power Station "B"');
insert into stationdata values('GRANGEAV',2,'Renewable/ Biomass / Waste','Landfill Methane / Landfill Gas','Combustion','Compression Reciprocating Engine','AGL Sales (Queensland Electricity) Pty Limited','Grange Avenue Power Station');
insert into stationdata values('BALDHWF1',106.6,'Wind','Wind','Renewable','Wind - Onshore','Alinta Energy Retail Sales Pty Ltd','Bald Hills Wind Farm');
insert into stationdata values('BOLIVAR1',9.9,'Renewable/ Biomass / Waste','Waste Water / Sewerage','Combustion','Compression Reciprocating Engine','Alinta Energy Retail Sales Pty Ltd','SA Water Bolivar Waste Water Treatment (WWT) Plant');
insert into stationdata values('BDL01',47,'Fossil','Natural Gas','Combustion','Open Cycle Gas turbines (OCGT)','Aurora Energy (Tamar Valley) Pty Ltd trading as AETV Power','Bairnsdale Power Station');
insert into stationdata values('BDL02',47,'Fossil','Natural Gas','Combustion','Open Cycle Gas turbines (OCGT)','Aurora Energy (Tamar Valley) Pty Ltd trading as AETV Power','Bairnsdale Power Station');
insert into stationdata values('BBTHREE1',35,'Fossil','Natural Gas','Combustion','Open Cycle Gas turbines (OCGT)','Aurora Energy (Tamar Valley) Pty Ltd trading as AETV Power','Bell Bay Three Power Station');
insert into stationdata values('BBTHREE2',35,'Fossil','Natural Gas','Combustion','Open Cycle Gas turbines (OCGT)','Aurora Energy (Tamar Valley) Pty Ltd trading as AETV Power','Bell Bay Three Power Station');
insert into stationdata values('BBTHREE3',35,'Fossil','Natural Gas','Combustion','Open Cycle Gas turbines (OCGT)','Aurora Energy (Tamar Valley) Pty Ltd trading as AETV Power','Bell Bay Three Power Station');
insert into stationdata values('TVCC201',208,'Fossil','Natural Gas','Combustion','Open Cycle Gas turbines (OCGT)','Aurora Energy (Tamar Valley) Pty Ltd trading as AETV Power','Tamar Valley Combined Cycle Power Station');
insert into stationdata values('TVCC201',,'Fossil','Natural Gas','Combustion','Closed Cycle Gas Turbines (CCGT)','Aurora Energy (Tamar Valley) Pty Ltd trading as AETV Power','Tamar Valley Combined Cycle Power Station');
insert into stationdata values('TVPP104',58,'Fossil','Natural Gas','Combustion','Open Cycle Gas turbines (OCGT)','Aurora Energy (Tamar Valley) Pty Ltd trading as AETV Power','Tamar Valley Peaking  Power Station');
insert into stationdata values('BLNKTAS',478,'','','','','Basslink Pty Ltd','Basslink HVDC Link');
insert into stationdata values('BLNKVIC',594,'','','','','Basslink Pty Ltd','Basslink HVDC Link');
insert into stationdata values('BOCORWF1',98.6,'Wind','Wind','Renewable','Wind - Onshore','Boco Rock Wind Farm Pty Ltd','Boco Rock Wind Farm');
insert into stationdata values('BOCORWF1',14.58,'Wind','Wind','Renewable','Wind - Onshore','Boco Rock Wind Farm Pty Ltd','Boco Rock Wind Farm');
insert into stationdata values('BRAEMAR1',168,'Fossil','Coal Seam Methane','Combustion','Open Cycle Gas turbines (OCGT)','Braemar Power Project Pty Ltd','Braemar Power Station ');
insert into stationdata values('BRAEMAR2',168,'Fossil','Coal Seam Methane','Combustion','Open Cycle Gas turbines (OCGT)','Braemar Power Project Pty Ltd','Braemar Power Station ');
insert into stationdata values('BRAEMAR3',168,'Fossil','Coal Seam Methane','Combustion','Open Cycle Gas turbines (OCGT)','Braemar Power Project Pty Ltd','Braemar Power Station ');
insert into stationdata values('CPP_3',420,'Fossil','Black Coal','Combustion','Steam Super Critical','Callide Power Trading Pty Limited','Callide Power Plant');
insert into stationdata values('CPP_4',420,'Fossil','Black Coal','Combustion','Steam Super Critical','Callide Power Trading Pty Limited','Callide Power Plant');
insert into stationdata values('-',46,'Wind','Wind','Renewable','Wind - Onshore','Canunda Power Pty Ltd','Canunda Wind Farm');
insert into stationdata values('-',,'Biomass','Bagasse','Combustion','Steam - sub critical','Cape Byron Management Pty Ltd','Broadwater Power Station Units 1 and 2');
insert into stationdata values('BWTR1',38,'Biomass','Bagasse','Combustion','Steam - sub critical','Cape Byron Management Pty Ltd','Broadwater Power Station Units 1 and 2');
insert into stationdata values('CONDONG1',30,'Biomass','Bagasse','Combustion','Steam - sub critical','Cape Byron Management Pty Ltd','Condong Power Station Unit 1');
insert into stationdata values('CATHROCK',66,'Wind','Wind','Renewable','Wind - Onshore','Cathedral Rocks Wind Farm Pty Ltd','Cathedral Rocks Wind Farm');
insert into stationdata values('CALL_A_4',30,'Fossil','Black Coal','Combustion','Steam Sub-Critical','CS Energy Limited','Callide A Power Station');
insert into stationdata values('CALL_B_1',350,'Fossil','Black Coal','Combustion','Steam Sub-Critical','CS Energy Limited','Callide B Power Station');
insert into stationdata values('CALL_B_2',350,'Fossil','Black Coal','Combustion','Steam Sub-Critical','CS Energy Limited','Callide B Power Station');
insert into stationdata values('GSTONE1',280,'Fossil','Black Coal','Combustion','Steam Sub-Critical','CS Energy Limited','Gladstone Power Station');
insert into stationdata values('GSTONE2',280,'Fossil','Black Coal','Combustion','Steam Sub-Critical','CS Energy Limited','Gladstone Power Station');
insert into stationdata values('GSTONE3',280,'Fossil','Black Coal','Combustion','Steam Sub-Critical','CS Energy Limited','Gladstone Power Station');
insert into stationdata values('GSTONE4',280,'Fossil','Black Coal','Combustion','Steam Sub-Critical','CS Energy Limited','Gladstone Power Station');
insert into stationdata values('GSTONE5',280,'Fossil','Black Coal','Combustion','Steam Sub-Critical','CS Energy Limited','Gladstone Power Station');
insert into stationdata values('GSTONE6',280,'Fossil','Black Coal','Combustion','Steam Sub-Critical','CS Energy Limited','Gladstone Power Station');
insert into stationdata values('KPP_1',744,'Fossil','Black Coal','Combustion','Steam Super Critical','CS Energy Limited','Kogan Creek Power Station');
insert into stationdata values('W/HOE#1',250,'Hydro','Water','Renewable','Hydro - pump storage','CS Energy Limited','Wivenhoe Power Station');
insert into stationdata values('W/HOE#2',250,'Hydro','Water','Renewable','Hydro - pump storage','CS Energy Limited','Wivenhoe Power Station');
insert into stationdata values('PUMP1',240,'','','','','CS Energy Limited','Wivenhoe Power Station No. 1 Pump');
insert into stationdata values('PUMP2',240,'','','','','CS Energy Limited','Wivenhoe Power Station No. 2 Pump');
insert into stationdata values('BROWNMT',4.95,'Hydro','Water','Renewable','Hydro - Gravity','Delta Electricity','Brown Mountain');
insert into stationdata values('BROWNMT',,'Hydro','Water','Renewable','Hydro - Gravity','Delta Electricity','Brown Mountain');
insert into stationdata values('BROWNMT',,'Hydro','Water','Renewable','Hydro - Gravity','Delta Electricity','Brown Mountain');
insert into stationdata values('BROWNMT',,'Hydro','Water','Renewable','Hydro - Gravity','Delta Electricity','Brown Mountain');
insert into stationdata values('VP5',660,'Fossil','Black Coal','Combustion','Steam Sub-Critical','Delta Electricity','Vales Point "B" Power Station');
insert into stationdata values('VP6',660,'Fossil','Black Coal','Combustion','Steam Sub-Critical','Delta Electricity','Vales Point "B" Power Station');
insert into stationdata values('SHEP1',1.1,'Renewable/ Biomass / Waste','Sewerage/Waste Water','Combustion','Compression Reciprocating Engine','Diamond Energy Pty Ltd ','Shepparton Wastewater Treatment Facility');
insert into stationdata values('TATURA01',1.1,'Renewable/ Biomass / Waste','Sewerage/Waste Water','Combustion','Compression Reciprocating Engine','Diamond Energy Pty Ltd ','Tatura Biomass Generator');
insert into stationdata values('JLA01',51,'Fossil','Natural Gas','Combustion','Open Cycle Gas turbines (OCGT)','Ecogen Energy Pty Ltd','Jeeralang "A" Power Station');
insert into stationdata values('JLA02',51,'Fossil','Natural Gas','Combustion','Open Cycle Gas turbines (OCGT)','Ecogen Energy Pty Ltd','Jeeralang "A" Power Station');
insert into stationdata values('JLA03',51,'Fossil','Natural Gas','Combustion','Open Cycle Gas turbines (OCGT)','Ecogen Energy Pty Ltd','Jeeralang "A" Power Station');
insert into stationdata values('JLA04',51,'Fossil','Natural Gas','Combustion','Open Cycle Gas turbines (OCGT)','Ecogen Energy Pty Ltd','Jeeralang "A" Power Station');
insert into stationdata values('JLB01',76,'Fossil','Natural Gas','Combustion','Open Cycle Gas turbines (OCGT)','Ecogen Energy Pty Ltd','Jeeralang "B" Power Station');
insert into stationdata values('JLB02',76,'Fossil','Natural Gas','Combustion','Open Cycle Gas turbines (OCGT)','Ecogen Energy Pty Ltd','Jeeralang "B" Power Station');
insert into stationdata values('JLB03',76,'Fossil','Natural Gas','Combustion','Open Cycle Gas turbines (OCGT)','Ecogen Energy Pty Ltd','Jeeralang "B" Power Station');
insert into stationdata values('NPS',500,'Fossil','Natural Gas','Combustion','Steam Sub-Critical','Ecogen Energy Pty Ltd','Newport Power Station');
insert into stationdata values('-',13.2,'Fossil','Waste Coal Mine Gas','Combustion','Compression Reciprocating Engine','EDL CSM (QLD) Pty Ltd','German Creek Power Station');
insert into stationdata values('GERMCRK',32,'Fossil','Waste Coal Mine Gas','Combustion','Compression Reciprocating Engine','EDL CSM (QLD) Pty Ltd','German Creek Power Station');
insert into stationdata values('-',55.6,'Fossil','Coal Seam Methane','Combustion','Spark Ignition Reciprocating Engine','EDL Group Operations Pty Ltd','Appin Power Plant');
insert into stationdata values('-',7.2,'Renewable/ Biomass / Waste','Landfill Methane / Landfill Gas','Combustion','Spark Ignition Reciprocating Engine','EDL Group Operations Pty Ltd','Berwick Power Plant');
insert into stationdata values('-',7.2,'Renewable/ Biomass / Waste','Landfill Methane / Landfill Gas','Combustion','Spark Ignition Reciprocating Engine','EDL Group Operations Pty Ltd','Broadmeadows Power Plant');
insert into stationdata values('-',41.2,'Fossil','Coal Seam Methane','Combustion','Spark Ignition Reciprocating Engine','EDL Group Operations Pty Ltd','Tower Power Plant');
insert into stationdata values('EASTCRK',5.4,'Renewable/ Biomass / Waste','Landfill Methane / Landfill Gas','Combustion','Compression Reciprocating Engine','EDL LFG (NSW) Pty Ltd','Eastern Creek Power Station');
insert into stationdata values('GRANGEAV',1.26,'Renewable/ Biomass / Waste','Landfill Methane / Landfill Gas','Combustion','Spark Ignition Reciprocating Engine','EDL LFG (NSW) Pty Ltd','Grange Avenue Landfill Gas Power Station');
insert into stationdata values('JACKSGUL',2.3,'Renewable/ Biomass / Waste','Landfill Methane / Landfill Gas','Combustion','Spark Ignition Reciprocating Engine','EDL LFG (NSW) Pty Ltd','Jacks Gully Landfill Gas Power Station');
insert into stationdata values('LUCAS2S2',13,'Renewable/ Biomass / Waste','Landfill Methane / Landfill Gas','Combustion','Compression Reciprocating Engine','EDL LFG (NSW) Pty Ltd','Lucas Heights 2 LFG Power Station');
insert into stationdata values('LUCASHGT',5,'Renewable/ Biomass / Waste','Landfill Methane / Landfill Gas','Combustion','Compression Reciprocating Engine','EDL LFG (NSW) Pty Ltd','Lucas Heights 2 LFG Power Station');
insert into stationdata values('BPLANDF1',2.18,'Renewable/ Biomass / Waste','Landfill Methane / Landfill Gas','Combustion','Spark Ignition Reciprocating Engine','EDL LFG (Qld) Pty Ltd','Browns Plains Land Fill Gas Power Station');
insert into stationdata values('HIGHBRY1',2,'Renewable/ Biomass / Waste','Landfill Methane / Landfill Gas','Combustion','Spark Ignition Reciprocating Engine','EDL LFG (SA) Pty Ltd','Highbury Landfill Gas Power Station Unit 1');
insert into stationdata values('PEDLER1',3,'Renewable/ Biomass / Waste','Landfill Methane / Landfill Gas','Combustion','Spark Ignition Reciprocating Engine','EDL LFG (SA) Pty Ltd','Pedler Creek Landfill Gas Power Station Units 1-3');
insert into stationdata values('TEATREE1',1,'Renewable/ Biomass / Waste','Landfill Methane / Landfill Gas','Combustion','Spark Ignition Reciprocating Engine','EDL LFG (SA) Pty Ltd','Tea Tree Gully Landfill Gas Power Station Unit 1');
insert into stationdata values('WING1_1',5,'Renewable/ Biomass / Waste','Landfill Methane / Landfill Gas','Combustion','Spark Ignition Reciprocating Engine','EDL LFG (SA) Pty Ltd','Wingfield 1 Landfill Gas Power Station Units 1-4');
insert into stationdata values('WING2_1',5,'Renewable/ Biomass / Waste','Landfill Methane / Landfill Gas','Combustion','Spark Ignition Reciprocating Engine','EDL LFG (SA) Pty Ltd','Wingfield 2 Landfill Gas Power Station Units 1-4');
insert into stationdata values('BROADMDW',5,'Renewable/ Biomass / Waste','Landfill Methane / Landfill Gas','Combustion','Spark Ignition Reciprocating Engine','EDL LFG (Vic) Pty Ltd','Broadmeadows Landfill Gas Power Station');
insert into stationdata values('-',,'Renewable','Landfill Gas','Combustion','Spark Ignition','EDL LFG (Vic) Pty Ltd','Brooklyn Landfill Gas Power Station');
insert into stationdata values('-',,'Renewable','Landfill Gas','Combustion','Spark Ignition','EDL LFG (Vic) Pty Ltd','Brooklyn Landfill Gas Power Station');
insert into stationdata values('BROOKLYN',2.83,'Renewable','Landfill Gas','Combustion','Spark Ignition','EDL LFG (Vic) Pty Ltd','Brooklyn Landfill Gas Power Station');
insert into stationdata values('CLAYTON',11,'Renewable','Landfill Gas','Combustion','Spark Ignition','EDL LFG (Vic) Pty Ltd','Claytons Landfill Gas Power Station');
insert into stationdata values('CORIO1',1,'Renewable/ Biomass / Waste','Landfill Methane / Landfill Gas','Combustion','Spark Ignition Reciprocating Engine','EDL LFG (VIC) Pty Ltd','Corio Landfill Gas Power Station');
insert into stationdata values('SVALE1',4.2,'Renewable/ Biomass / Waste','Landfill Methane / Landfill Gas','Combustion','Spark Ignition Reciprocating Engine','EDL LFG (VIC) Pty Ltd','Springvale Landfill Gas Power Station');
insert into stationdata values('MBAHNTH',63,'Renewable','Waste Coal Mine Gas','Combustion','Spark Ignition','EDL Projects (Australia) Pty Ltd','Moranbah North Power Station');
insert into stationdata values('MOR1',90,'Fossil','Brown Coal','Combustion','Steam Sub-Critical','Energy Brix Australia Corporation Pty Ltd','Energy Brix Complex Power Station');
insert into stationdata values('MOR1',,'Fossil','Brown Coal','Combustion','Steam Sub-Critical','Energy Brix Australia Corporation Pty Ltd','Energy Brix Complex Power Station');
insert into stationdata values('MOR2',30,'Fossil','Brown Coal','Combustion','Steam Sub-Critical','Energy Brix Australia Corporation Pty Ltd','Energy Brix Complex Power Station');
insert into stationdata values('MOR3',75,'Fossil','Brown Coal','Combustion','Steam Sub-Critical','Energy Brix Australia Corporation Pty Ltd','Energy Brix Complex Power Station');
insert into stationdata values('-',18.2,'Wind','Wind','Renewable','Wind - Onshore','Energy Pacific (Vic) Pty Ltd','Codrington Wind Farm');
insert into stationdata values('YAMBUKWF',30,'Wind','Wind','Renewable','Wind - Onshore','Energy Pacific (Vic) Pty Ltd','Yambuk Wind Farm ');
insert into stationdata values('AGLHAL',180,'Fossil','Natural Gas / Diesel','Combustion','Combined Cycle Gas Turbine (CCGT)','EnergyAustralia Pty Ltd','Hallett Power Station');
insert into stationdata values('AGLHAL',,'Fossil','Natural Gas / Diesel','Combustion','Combined Cycle Gas Turbine (CCGT)','EnergyAustralia Pty Ltd','Hallett Power Station');
insert into stationdata values('AGLHAL',,'Fossil','Natural Gas / Diesel','Combustion','Combined Cycle Gas Turbine (CCGT)','EnergyAustralia Pty Ltd','Hallett Power Station');
insert into stationdata values('AGLHAL',,'Fossil','Natural Gas / Diesel','Combustion','Combined Cycle Gas Turbine (CCGT)','EnergyAustralia Pty Ltd','Hallett Power Station');
insert into stationdata values('MORNW',1,'Renewable/ Biomass / Waste','Landfill Methane / Landfill Gas','Combustion','Compression Reciprocating Engine','EnergyAustralia Pty Ltd','Mornington Waste Disposal Facility');
insert into stationdata values('MP1',700,'Fossil','Black Coal','Combustion','Steam Sub-Critical','EnergyAustralia Pty Ltd','Mt Piper Power Station');
insert into stationdata values('MP2',700,'Fossil','Black Coal','Combustion','Steam Sub-Critical','EnergyAustralia Pty Ltd','Mt Piper Power Station');
insert into stationdata values('TALWA1',460,'Fossil','Natural Gas','Combustion','Combined Cycle Gas Turbine (CCGT)','EnergyAustralia Pty Ltd','Tallawarra Power Station');
insert into stationdata values('WDLNGN01',7,'Renewable/ Biomass / Waste','Landfill Methane / Landfill Gas','Combustion','Compression Reciprocating Engine','EnergyAustralia Pty Ltd','Woodlawn Bioreactor Energy Generation Station');
insert into stationdata values('WYNDW',1,'Renewable/ Biomass / Waste','Landfill Methane / Landfill Gas','Combustion','Compression Reciprocating Engine','EnergyAustralia Pty Ltd','Wyndham Waste Disposal Facility');
insert into stationdata values('YWPS1',360,'Fossil','Brown Coal','Combustion','Steam Sub-Critical','EnergyAustralia Yallourn Pty Ltd','Yallourn W Power Station');
insert into stationdata values('YWPS2',360,'Fossil','Brown Coal','Combustion','Steam Sub-Critical','EnergyAustralia Yallourn Pty Ltd','Yallourn W Power Station');
insert into stationdata values('YWPS3',380,'Fossil','Brown Coal','Combustion','Steam Sub-Critical','EnergyAustralia Yallourn Pty Ltd','Yallourn W Power Station');
insert into stationdata values('YWPS4',380,'Fossil','Brown Coal','Combustion','Steam Sub-Critical','EnergyAustralia Yallourn Pty Ltd','Yallourn W Power Station');
insert into stationdata values('AMCORGR',4,'Fossil','Diesel','Combustion','Compression Reciprocating Engine','EnerNOC Pty Ltd','Amcor Glass, Gawler Plant');
insert into stationdata values('BBASEHOS',3,'Fossil','Natural Gas','Combustion','Compression Reciprocating Engine','EnerNOC Pty Ltd','Ballarat Base Hospital Plant');
insert into stationdata values('BANKSPT1',2,'Fuel Oil','Diesel','Combustion','Compression Reciprocating Engine','EnerNOC Pty Ltd','Bankstown Sports Club Plant Units ');
insert into stationdata values('BANKSPT1',,'Fuel Oil','Diesel','Combustion','Compression Reciprocating Engine','EnerNOC Pty Ltd','Bankstown Sports Club Plant Units ');
insert into stationdata values('BLULAKE1',1,'Fossil','Diesel','Combustion','Compression Reciprocating Engine','EnerNOC Pty Ltd','Blue Lake Milling Power Plant');
insert into stationdata values('NINEWIL1',3.2,'Fuel Oil','Diesel','Combustion','Compression Reciprocating Engine','EnerNOC Pty Ltd','Nine Network Willoughby Plant ');
insert into stationdata values('STGEORG1',1,'Fuel Oil','Diesel','Combustion','Compression Reciprocating Engine','EnerNOC Pty Ltd','St George Leagues Club Plant');
insert into stationdata values('TATIARA1',0.5,'Fuel Oil','Diesel','Combustion','Compression Reciprocating Engine','EnerNOC Pty Ltd','Tatiara Bordertown Plant');
insert into stationdata values('WESTILL1',1,'Fuel Oil','Diesel','Combustion','Compression Reciprocating Engine','EnerNOC Pty Ltd','West Illawarra Leagues Club Plant');
insert into stationdata values('WESTILL1',,'Fuel Oil','Diesel','Combustion','Compression Reciprocating Engine','EnerNOC Pty Ltd','West Illawarra Leagues Club Plant');
insert into stationdata values('WESTCBT1',1,'Fuel Oil','Diesel','Combustion','Compression Reciprocating Engine','EnerNOC Pty Ltd','Western Suburbs League Club (Campbelltown) Plant');
insert into stationdata values('-',13,'Fossil','Coal Seam Methane','Combustion','Compression Reciprocating Engine','Envirogen (Oaky) Pty Limited','Glennies Creek Power Station ');
insert into stationdata values('TERALBA',3,'Fossil','Coal Seam Methane','Combustion','Compression Reciprocating Engine','EnviroGen Pty Limited','Teralba Power Station ');
insert into stationdata values('BARCALDN',37,'Fossil','Natural Gas','Combustion','Combined Cycle Gas Turbine (CCGT)','Ergon Energy Queensland Pty Ltd','Barcaldine Power Station');
insert into stationdata values('OAKEY1',141,'Fossil','Natural Gas','Combustion','Open Cycle Gas turbines (OCGT)','ERM Power Retail Pty Ltd','Oakey Power Station');
insert into stationdata values('OAKEY2',141,'Fossil','Natural Gas','Combustion','Open Cycle Gas turbines (OCGT)','ERM Power Retail Pty Ltd','Oakey Power Station');
insert into stationdata values('GB01',50,'Fossil','Diesel','Combustion','Open Cycle Gas turbines (OCGT)','Essential Energy','Broken Hill Gas Turbines');
insert into stationdata values('NPS1',265,'Fossil','Brown Coal','Combustion','Steam Sub-Critical','Flinders Operating Services Pty Ltd','Northern Power Station');
insert into stationdata values('NPS2',265,'Fossil','Brown Coal','Combustion','Steam Sub-Critical','Flinders Operating Services Pty Ltd','Northern Power Station');
insert into stationdata values('PLAYB-AG',240,'Fossil','Brown Coal','Combustion','Steam Sub-Critical','Flinders Operating Services Pty Ltd','Playford B Power Station');
insert into stationdata values('RPCG',30,'','','','','FPC 30 Limited (as Trustee for the FPC Green Trust)','Rocky Point Cogeneration Plant');
insert into stationdata values('ROYALLA1',20,'Solar','Solar PV','Renewable','Photovoltaic Flat Panel','FRV Royalla Solar Farm Pty Ltd','Royalla Solar Farm');
insert into stationdata values('BURRIN',27,'Hydro','Water','Renewable','Hydro - Gravity','GSP Energy Pty Ltd','Burrinjuck Power Station');
insert into stationdata values('BURRIN',,'Hydro','Water','Renewable','Hydro - Gravity','GSP Energy Pty Ltd','Burrinjuck Power Station');
insert into stationdata values('HUMENSW',29,'Hydro','Water','Renewable','Hydro - Gravity','GSP Energy Pty Ltd','Hume Power Station');
insert into stationdata values('HUMEV',29,'Hydro','Water','Renewable','Hydro - Gravity','GSP Energy Pty Ltd','Hume Power Station');
insert into stationdata values('KEEPIT',6,'Hydro','Water','Renewable','Hydro - Gravity','GSP Energy Pty Ltd','Keepit Power Station');
insert into stationdata values('GUNNING1',47,'Wind','Wind','Wind','Wind - Onshore','Gunning Wind Energy Developments Pty Ltd','Gunning Wind Farm');
insert into stationdata values('HWPS1',200,'Fossil','Brown Coal','Combustion','Steam Sub-Critical','Hazelwood Power','Hazelwood Power Station');
insert into stationdata values('HWPS2',200,'Fossil','Brown Coal','Combustion','Steam Sub-Critical','Hazelwood Power','Hazelwood Power Station');
insert into stationdata values('HWPS3',200,'Fossil','Brown Coal','Combustion','Steam Sub-Critical','Hazelwood Power','Hazelwood Power Station');
insert into stationdata values('HWPS4',200,'Fossil','Brown Coal','Combustion','Steam Sub-Critical','Hazelwood Power','Hazelwood Power Station');
insert into stationdata values('HWPS5',200,'Fossil','Brown Coal','Combustion','Steam Sub-Critical','Hazelwood Power','Hazelwood Power Station');
insert into stationdata values('HWPS6',200,'Fossil','Brown Coal','Combustion','Steam Sub-Critical','Hazelwood Power','Hazelwood Power Station');
insert into stationdata values('HWPS7',200,'Fossil','Brown Coal','Combustion','Steam Sub-Critical','Hazelwood Power','Hazelwood Power Station');
insert into stationdata values('HWPS8',200,'Fossil','Brown Coal','Combustion','Steam Sub-Critical','Hazelwood Power','Hazelwood Power Station');
insert into stationdata values('WYANGALA',20,'Hydro','Water','Renewable','Hydro - Gravity','Hydro Power Pty Limited','Wyangala A Power Station');
insert into stationdata values('WYANGALB',4,'Hydro','Water','Renewable','Hydro - Gravity','Hydro Power Pty Limited','Wyangala B Power Station');
insert into stationdata values('BASTYAN',79.9,'Hydro','Water','Renewable','Hydro - Gravity','Hydro-Electric Corporation trading as Hydro Tasmania','Bastyan Power Station');
insert into stationdata values('BUTLERSG',14.4,'Hydro','Water','Renewable','Hydro - Gravity','Hydro-Electric Corporation trading as Hydro Tasmania','Butlers Gorge Power Station');
insert into stationdata values('LI_WY_CA',170.1,'Hydro','Water','Renewable','Hydro - Gravity','Hydro-Electric Corporation trading as Hydro Tasmania','Catagunya / Liapootah / Wayatinah Power Station');
insert into stationdata values('LI_WY_CA',,'Hydro','Water','Renewable','Hydro - Gravity','Hydro-Electric Corporation trading as Hydro Tasmania','Catagunya / Liapootah / Wayatinah Power Station');
insert into stationdata values('LI_WY_CA',,'Hydro','Water','Renewable','Hydro - Gravity','Hydro-Electric Corporation trading as Hydro Tasmania','Catagunya / Liapootah / Wayatinah Power Station');
insert into stationdata values('CETHANA',85,'Hydro','Water','Renewable','Hydro - Gravity','Hydro-Electric Corporation trading as Hydro Tasmania','Cethana Power Station');
insert into stationdata values('CLUNY',17,'Hydro','Water','Renewable','Hydro - Gravity','Hydro-Electric Corporation trading as Hydro Tasmania','Cluny Power Station');
insert into stationdata values('DEVILS_G',60,'Hydro','Water','Renewable','Hydro - Gravity','Hydro-Electric Corporation trading as Hydro Tasmania','Devils Gate Power Station');
insert into stationdata values('FISHER',43.2,'Hydro','Water','Renewable','Hydro - Gravity','Hydro-Electric Corporation trading as Hydro Tasmania','Fisher Power Station');
insert into stationdata values('GORDON',432,'Hydro','Water','Renewable','Hydro - Gravity','Hydro-Electric Corporation trading as Hydro Tasmania','Gordon Power Station');
insert into stationdata values('JBUTTERS',144,'Hydro','Water','Renewable','Hydro - Gravity','Hydro-Electric Corporation trading as Hydro Tasmania','John Butters Power Station');
insert into stationdata values('LK_ECHO',32.4,'Hydro','Water','Renewable','Hydro - Gravity','Hydro-Electric Corporation trading as Hydro Tasmania','Lake Echo Power Station');
insert into stationdata values('LEM_WIL',81.6,'Hydro','Water','Renewable','Hydro - Gravity','Hydro-Electric Corporation trading as Hydro Tasmania','Lemonthyme / Wilmot  Power Station');
insert into stationdata values('LEM_WIL',,'Hydro','Water','Renewable','Hydro - Gravity','Hydro-Electric Corporation trading as Hydro Tasmania','Lemonthyme / Wilmot  Power Station');
insert into stationdata values('MACKNTSH',79.9,'Hydro','Water','Renewable','Hydro - Gravity','Hydro-Electric Corporation trading as Hydro Tasmania','Mackintosh Power Station');
insert into stationdata values('MEADOWBK',40,'Hydro','Water','Renewable','Hydro - Gravity','Hydro-Electric Corporation trading as Hydro Tasmania','Meadowbank Power Station');
insert into stationdata values('MUSSELR1',168,'Wind','Wind','Renewable','Wind - Onshore','Hydro-Electric Corporation trading as Hydro Tasmania','Musselroe Wind Farm');
insert into stationdata values('PALOONA',28,'Hydro','Water','Renewable','Hydro - Gravity','Hydro-Electric Corporation trading as Hydro Tasmania','Paloona Power Station');
insert into stationdata values('POAT110',100,'Hydro','Water','Renewable','Hydro - Gravity','Hydro-Electric Corporation trading as Hydro Tasmania','Poatina Power Station');
insert into stationdata values('POAT220',200,'Hydro','Water','Renewable','Hydro - Gravity','Hydro-Electric Corporation trading as Hydro Tasmania','Poatina Power Station');
insert into stationdata values('REECE1',115.6,'Hydro','Water','Renewable','Hydro - Gravity','Hydro-Electric Corporation trading as Hydro Tasmania','Reece Power Station');
insert into stationdata values('REECE2',115.6,'Hydro','Water','Renewable','Hydro - Gravity','Hydro-Electric Corporation trading as Hydro Tasmania','Reece Power Station');
insert into stationdata values('REPULSE',28,'Hydro','Water','Renewable','Hydro - Gravity','Hydro-Electric Corporation trading as Hydro Tasmania','Repulse Power Station');
insert into stationdata values('ROWALLAN',10.5,'Hydro','Water','Renewable','Hydro - Gravity','Hydro-Electric Corporation trading as Hydro Tasmania','Rowallan Power Station');
insert into stationdata values('TARRALEA',90,'Hydro','Water','Renewable','Hydro - Gravity','Hydro-Electric Corporation trading as Hydro Tasmania','Tarraleah Power Station');
insert into stationdata values('TERMSTOR',2.5,'Hydro','Water','Renewable','Hydro - Gravity','Hydro-Electric Corporation trading as Hydro Tasmania','Terminal Storage Mini Hydro Power Station');
insert into stationdata values('TREVALLN',80,'Hydro','Water','Renewable','Hydro - Gravity','Hydro-Electric Corporation trading as Hydro Tasmania','Trevallyn Power Station');
insert into stationdata values('TRIBUTE',82.8,'Hydro','Water','Renewable','Hydro - Gravity','Hydro-Electric Corporation trading as Hydro Tasmania','Tribute Power Station');
insert into stationdata values('TUNGATIN',125,'Hydro','Water','Renewable','Hydro - Gravity','Hydro-Electric Corporation trading as Hydro Tasmania','Tungatinah Power Station');
insert into stationdata values('WOOLNTH1',140,'Wind','Wind','Renewable','Wind - Onshore','Hydro-Electric Corporation trading as Hydro Tasmania','Woolnorth Studland Bay / Bluff Point Wind Farm');
insert into stationdata values('WOOLNTH1',,'Wind','Wind','Renewable','Wind - Onshore','Hydro-Electric Corporation trading as Hydro Tasmania','Woolnorth Studland Bay / Bluff Point Wind Farm');
insert into stationdata values('CESF1',1,'Solar','Solar PV','Renewable','PV - Panels','Infigen Energy  Holdings Pty Ltd','Capital East Solar Farm');
insert into stationdata values('CESF1',,'Solar','Solar PV','Renewable','PV - Panels','Infigen Energy  Holdings Pty Ltd','Capital East Solar Farm');
insert into stationdata values('CESF1',,'Solar','Solar PV','Renewable','PV - Panels','Infigen Energy  Holdings Pty Ltd','Capital East Solar Farm');
insert into stationdata values('CAPTL_WF',140,'Wind','Wind','Renewable','Wind - Onshore','Infigen Energy Markets Pty Limited','Capital Wind Farm');
insert into stationdata values('LOYYB1',500,'Fossil','Brown Coal','Combustion','Steam Sub-Critical','IPM Australia Limited ','Loy Yang B Power Station');
insert into stationdata values('LOYYB2',500,'Fossil','Brown Coal','Combustion','Steam Sub-Critical','IPM Australia Limited ','Loy Yang B Power Station');
insert into stationdata values('LKBONNY1',80.5,'Wind','Wind','Renewable','Wind - Onshore','Lake Bonney Wind Power Pty Ltd','Lake Bonney Wind Farm');
insert into stationdata values('LKBONNY2',159,'Wind','Wind','Renewable','Wind - Onshore','Lake Bonney Wind Power Pty Ltd','Lake Bonney Stage 2 Windfarm');
insert into stationdata values('LKBONNY3',39,'Wind','Wind','Renewable','Wind - Onshore','Lake Bonney Wind Power Pty Ltd','Lake Bonney Stage 3 Wind Farm');
insert into stationdata values('-',8.984,'','','','','LMS Energy Pty Ltd','Eastern Creek 2 Gas Utilisation Facility ');
insert into stationdata values('HALLAMRD1',8.984,'Renewable/ Biomass / Waste','Landfill Methane / Landfill Gas','Combustion','Spark Ignition Reciprocating Engine','Lumo Energy Australia Pty Ltd','Hallam Road Renewable Energy Facility');
insert into stationdata values('WOLLERT1',6.738,'Renewable/ Biomass / Waste','Landfill Methane / Landfill Gas','Combustion','Spark Ignition Reciprocating Engine','Lumo Energy Australia Pty Ltd','Wollert Renewable Energy Facility');
insert into stationdata values('ANGAS1',30,'Fossil','Diesel','Combustion','Compression Reciprocating Engine','LUMO Generation SA Pty Ltd','Angaston Power Station');
insert into stationdata values('ANGAS2',20,'Fossil','Diesel','Combustion','Compression Reciprocating Engine','LUMO Generation SA Pty Ltd','Angaston Power Station');
insert into stationdata values('AWABAREF',1.123,'Renewable/ Biomass / Waste','Landfill Methane / Landfill Gas','','','LUMO Generation SA Pty Ltd','Awaba Power Station');
insert into stationdata values('HEZ',29,'Fossil','Diesel','','','LUMO Generation SA Pty Ltd','Hunter Economic Zone');
insert into stationdata values('LONSDALE',20,'Fossil','Diesel','Combustion','Compression Reciprocating Engine','LUMO Generation SA Pty Ltd','Lonsdale Power Station');
insert into stationdata values('STANV1',28.8,'Fossil','Diesel','Combustion','Compression Reciprocating Engine','LUMO Generation SA Pty Ltd','Port Stanvac Power Station 1');
insert into stationdata values('STANV2',28.8,'Fossil','Diesel','Combustion','Compression Reciprocating Engine','LUMO Generation SA Pty Ltd','Port Stanvac Power Station 2');
insert into stationdata values('REMOUNT',2,'Renewable/ Biomass / Waste','Landfill Methane / Landfill Gas','','','LUMO Generation SA Pty Ltd','Remount Power Station');
insert into stationdata values('-',3.5,'Renewable/ Biomass / Waste','Bagasse','Combustion','Steam Sub-Critical','Mackay Sugar Limited','Racecourse Mill');
insert into stationdata values('-',7,'Renewable/ Biomass / Waste','Bagasse','Combustion','Steam Sub-Critical','Mackay Sugar Limited','Racecourse Mill');
insert into stationdata values('-',38,'Renewable/ Biomass / Waste','Bagasse','Combustion','Steam Sub-Critical','Mackay Sugar Limited','Racecourse Mill');
insert into stationdata values('SITHE01',160,'Fossil','Natural Gas','Combustion','Combined Cycle Gas Turbine (CCGT)','Marubeni Australia Power Services Pty Ltd','Smithfield Energy Facility');
insert into stationdata values('SITHE01',,'Fossil','Natural Gas','Combustion','Combined Cycle Gas Turbine (CCGT)','Marubeni Australia Power Services Pty Ltd','Smithfield Energy Facility');
insert into stationdata values('MPP_1',426,'Fossil','Black Coal','Combustion','Steam Super Critical','Millmerran Energy Trader Pty Ltd','Millmerran Power Plant');
insert into stationdata values('MPP_2',426,'Fossil','Black Coal','Combustion','Steam Super Critical','Millmerran Energy Trader Pty Ltd','Millmerran Power Plant');
insert into stationdata values('MLWF1',20,'Wind','Wind','Renewable','Wind - Onshore','Mortons Lane Windfarm Pty Limited','Mortons Lane Wind Farm');
insert into stationdata values('MERCER01',131,'Wind','Wind','Renewable','Wind - Onshore','Mt Mercer Windfarm Pty Ltd','Mt Mercer Windf Farm');
insert into stationdata values('MTMILLAR',70,'Wind','Wind','Renewable','Wind - Onshore','Mt Millar Wind Farm Pty Ltd','Mt Millar Wind Farm');
insert into stationdata values('-',4,'Fossil','Coal Seam Methane','Combustion','Compression Reciprocating Engine','Narrabri Power Limited','Wilga Park Power Station');
insert into stationdata values('-',6,'Fossil','Coal Seam Methane','Combustion','Compression Reciprocating Engine','Narrabri Power Limited','Wilga Park Power Station');
insert into stationdata values(' - ',  ,'Wind','Wind','Renewable','Wind - Onshore','New Gullen Range Wind Farm Pty Ltd','Gullen Range Wind Farm');
insert into stationdata values('GULLRWF1',166,'Wind','Wind','Renewable','Wind - Onshore','New Gullen Range Wind Farm Pty Ltd','Gullen Range Wind Farm');
insert into stationdata values('BRAEMAR5',173,'Fossil','Coal Seam Methane','Combustion','Open Cycle Gas turbines (OCGT)','NewGen Braemar 2 Partnership','Braemar 2 Power Station');
insert into stationdata values('BRAEMAR6',173,'Fossil','Coal Seam Methane','Combustion','Open Cycle Gas turbines (OCGT)','NewGen Braemar 2 Partnership','Braemar 2 Power Station');
insert into stationdata values('BRAEMAR7',173,'Fossil','Coal Seam Methane','Combustion','Open Cycle Gas turbines (OCGT)','NewGen Braemar 2 Partnership','Braemar 2 Power Station');
insert into stationdata values('TGNSS1',10,'Fossil','Natural Gas','Combustion','Spark Ignition Reciprocating Engine','NovaPower Pty Ltd','Taralgon Network Support Station');
insert into stationdata values('SHGEN ',240,'Hydro','Water','Renewable','Hydro - Gravity','Origin Energy Electricity Limited','Bendeela / Kangaroo Valley Power Station');
insert into stationdata values('SHGEN ',,'Hydro','Water','Renewable','Hydro - Gravity','Origin Energy Electricity Limited','Bendeela / Kangaroo Valley Power Station');
insert into stationdata values('SHPUMP',240,'','','','','Origin Energy Electricity Limited','Bendeela / Kangaroo Valley Pumps');
insert into stationdata values('SHPUMP',,'','','','','Origin Energy Electricity Limited','Bendeela / Kangaroo Valley Pumps');
insert into stationdata values('CULLRGWF',30,'Wind','Wind','Renewable','Wind - Onshore','Origin Energy Electricity Limited','Cullerin Range Wind Farm');
insert into stationdata values('DAANDINE',33,'Fossil','Coal Seam Methane','Combustion','Compression Reciprocating Engine','Origin Energy Electricity Limited','Daandine Power Station');
insert into stationdata values('DDPS1',644,'Fossil','Natural Gas','Combustion','Combined Cycle Gas Turbine (CCGT)','Origin Energy Electricity Limited','Darling Downs Power Station');
insert into stationdata values('DDPS1',_,'Fossil','Natural Gas','Combustion','Combined Cycle Gas Turbine (CCGT)','Origin Energy Electricity Limited','Darling Downs Power Station');
insert into stationdata values('ER01',720,'Fossil','Black Coal','Combustion','Steam Sub-Critical','Origin Energy Electricity Limited','Eraring Power Station');
insert into stationdata values('ER02',720,'Fossil','Black Coal','Combustion','Steam Sub-Critical','Origin Energy Electricity Limited','Eraring Power Station');
insert into stationdata values('ER03',720,'Fossil','Black Coal','Combustion','Steam Sub-Critical','Origin Energy Electricity Limited','Eraring Power Station');
insert into stationdata values('ER04',720,'Fossil','Black Coal','Combustion','Steam Sub-Critical','Origin Energy Electricity Limited','Eraring Power Station');
insert into stationdata values('ERGT01',41.5,'Fossil','Diesel','Combustion','Compression Reciprocating Engine','Origin Energy Electricity Limited','Eraring Power Station');
insert into stationdata values('LADBROK1',40,'Fossil','Natural Gas','Combustion','Open Cycle Gas turbines (OCGT)','Origin Energy Electricity Limited','Ladbroke Grove Power Station');
insert into stationdata values('LADBROK2',40,'Fossil','Natural Gas','Combustion','Open Cycle Gas turbines (OCGT)','Origin Energy Electricity Limited','Ladbroke Grove Power Station');
insert into stationdata values('LONGFORD',31,'Fossil','Natural Gas','','','Origin Energy Electricity Limited','Longford Plant');
insert into stationdata values('MORTLK11',283,'Fossil','Natural Gas','Combustion','Open Cycle Gas turbines (OCGT)','Origin Energy Electricity Limited','Mortlake Power Station Units');
insert into stationdata values('MORTLK12',283,'Fossil','Natural Gas','Combustion','Open Cycle Gas turbines (OCGT)','Origin Energy Electricity Limited','Mortlake Power Station Units');
insert into stationdata values('MSTUART1',146,'Fossil','Kerosene','Combustion','Open Cycle Gas turbines (OCGT)','Origin Energy Electricity Limited','Mt Stuart Power Station');
insert into stationdata values('MSTUART2',146,'Fossil','Kerosene','Combustion','Open Cycle Gas turbines (OCGT)','Origin Energy Electricity Limited','Mt Stuart Power Station');
insert into stationdata values('MSTUART3',131,'Fossil','Kerosene','Combustion','Open Cycle Gas turbines (OCGT)','Origin Energy Electricity Limited','Mt Stuart Power Station');
insert into stationdata values('OAKYCREK',20,'Fossil','Coal Seam Methane','Combustion','Compression Reciprocating Engine','Origin Energy Electricity Limited','Oaky Creek  Power Station');
insert into stationdata values('OAKYCREK',,'Fossil','Coal Seam Methane','Combustion','Compression Reciprocating Engine','Origin Energy Electricity Limited','Oaky Creek  Power Station');
insert into stationdata values('OSB-AG',180,'Fossil','Natural Gas','Combustion','Combined Cycle Gas Turbine (CCGT)','Origin Energy Electricity Limited','Osborne Power Station');
insert into stationdata values('OSB-AG',,'Fossil','Natural Gas','Combustion','Combined Cycle Gas Turbine (CCGT)','Origin Energy Electricity Limited','Osborne Power Station');
insert into stationdata values('QPS1',24,'Fossil','Natural Gas','Combustion','Open Cycle Gas turbines (OCGT)','Origin Energy Electricity Limited','Quarantine Power Station');
insert into stationdata values('QPS2',24,'Fossil','Natural Gas','Combustion','Open Cycle Gas turbines (OCGT)','Origin Energy Electricity Limited','Quarantine Power Station');
insert into stationdata values('QPS3',24,'Fossil','Natural Gas','Combustion','Open Cycle Gas turbines (OCGT)','Origin Energy Electricity Limited','Quarantine Power Station');
insert into stationdata values('QPS4',24,'Fossil','Natural Gas','Combustion','Open Cycle Gas turbines (OCGT)','Origin Energy Electricity Limited','Quarantine Power Station');
insert into stationdata values('QPS5',128,'Fossil','Natural Gas','Combustion','Open Cycle Gas turbines (OCGT)','Origin Energy Electricity Limited','Quarantine Power Station');
insert into stationdata values('ROCHEDAL',4,'Renewable/ Biomass / Waste','Landfill Methane / Landfill Gas','Combustion','Compression Reciprocating Engine','Origin Energy Electricity Limited','Rochedale Renewable Energy Facility');
insert into stationdata values('ROCHEDAL',,'Renewable/ Biomass / Waste','Landfill Methane / Landfill Gas','Combustion','Compression Reciprocating Engine','Origin Energy Electricity Limited','Rochedale Renewable Energy Facility');
insert into stationdata values('ROMA_7',40,'Fossil','Natural Gas','Combustion','Open Cycle Gas turbines (OCGT)','Origin Energy Electricity Limited','Roma Gas Turbine Station');
insert into stationdata values('ROMA_8',40,'Fossil','Natural Gas','Combustion','Open Cycle Gas turbines (OCGT)','Origin Energy Electricity Limited','Roma Gas Turbine Station');
insert into stationdata values('WHIT1',1,'Renewable/ Biomass / Waste','Landfill Methane / Landfill Gas','Combustion','Compression Reciprocating Engine','Origin Energy Electricity Limited','Whitwood Road Renewable Energy Facility');
insert into stationdata values('WONWP',12,'Wind','','Renewable','Wind - Onshore','Origin Energy Electricity Limited','Wonthaggi Wind Farm');
insert into stationdata values('URANQ11',166,'Fossil','Natural Gas','Combustion','Open Cycle Gas turbines (OCGT)','Origin Energy Uranquinty Power Pty Ltd','Uranquinty Power Station ');
insert into stationdata values('URANQ12',166,'Fossil','Natural Gas','Combustion','Open Cycle Gas turbines (OCGT)','Origin Energy Uranquinty Power Pty Ltd','Uranquinty Power Station ');
insert into stationdata values('URANQ13',166,'Fossil','Natural Gas','Combustion','Open Cycle Gas turbines (OCGT)','Origin Energy Uranquinty Power Pty Ltd','Uranquinty Power Station ');
insert into stationdata values('URANQ14',166,'Fossil','Natural Gas','Combustion','Open Cycle Gas turbines (OCGT)','Origin Energy Uranquinty Power Pty Ltd','Uranquinty Power Station ');
insert into stationdata values('-',52.5,'Wind','Wind','Renewable','Wind - Onshore','Pacific Hydro Challicum Hills Pty Ltd','Challicum Hills Wind Farm');
insert into stationdata values('CLEMGPWF',57,'Wind','Wind','Renewable','Wind - Onshore','Pacific Hydro Clements Gap Pty Ltd','Clements Gap Wind Farm');
insert into stationdata values('EILDON3',5,'Hydro','Water','Renewable','Run of River','Pacific Hydro Investments Pty Ltd','Eildon Pondage Hydro Power Station');
insert into stationdata values('GLENMAG1',4,'Hydro','Water','Renewable','Run of River','Pacific Hydro Investments Pty Ltd','Glenmaggie Hydro Power Station');
insert into stationdata values('THEDROP1',3,'Hydro','Water','Renewable','Run of River','Pacific Hydro Investments Pty Ltd','The Drop Hydro Unit 1');
insert into stationdata values('WILLHOV1',2,'Hydro','Water','Renewable','Run of River','Pacific Hydro Investments Pty Ltd','William Hovell Hydro Power Station');
insert into stationdata values('-',148,'Wind','Wind','Renewable','Wind - Onshore','Pacific Hydro Portland Wind Farm Pty Ltd','Portland Wind Farm');
insert into stationdata values('PPCCGT',478,'Fossil','Natural Gas','Combustion','Combined Cycle Gas Turbine (CCGT)','Pelican Point Power Limited','Pelican Point Power Station');
insert into stationdata values('PPCCGT',,'Fossil','Natural Gas','Combustion','Combined Cycle Gas Turbine (CCGT)','Pelican Point Power Limited','Pelican Point Power Station');
insert into stationdata values('-',30.86,'Renewable/ Biomass / Waste','Bagasse','Combustion','Steam Sub-Critical','Pioneer Sugar Mills Pty Ltd','Pioneer Sugar Mill');
insert into stationdata values('-',36.92,'Renewable/ Biomass / Waste','Bagasse','Combustion','Steam Sub-Critical','Pioneer Sugar Mills Pty Ltd','Pioneer Sugar Mill');
insert into stationdata values('HLMSEW01',0.25,'Hydro','Water','Renewable','Hydro - Gravity','Progressive Green Pty Ltd','South East Water - Hallam Hydro Plant');
insert into stationdata values('WAUBRAWF',192,'Wind','Wind','Renewable','Wind - Onshore','Pyrenees Wind Energy Development Pty Ltd','Waubra Wind Farm');
insert into stationdata values('CPSA',144,'Fossil','Natural Gas','Combustion','Combined Cycle Gas Turbine (CCGT)','QGC Sales Qld Pty Ltd','Condamine Power Station A');
insert into stationdata values('CPSA',,'Fossil','Natural Gas','Combustion','Combined Cycle Gas Turbine (CCGT)','QGC Sales Qld Pty Ltd','Condamine Power Station A');
insert into stationdata values('HEPWIND1',4.1,'Wind','Wind','Renewable','Wind - Onshore','Red Energy Pty Limited','Hepburn Wind Farm');
insert into stationdata values('YARWUN_1',154,'','','','','RTA Yarwun Pty Ltd','Yarwun Power Station');
insert into stationdata values('WILGAPK',10,'Fossil','Coal Seam Methane','Combustion','Spark Ignition Reciprocating Engine','SANTOS NSW (NARRABRI POWER) PTY LTD ','Wilga Park A Power Station');
insert into stationdata values('WILGB01',6,'Fossil','Coal Seam Methane','Combustion','Spark Ignition Reciprocating Engine','SANTOS NSW (NARRABRI POWER) PTY LTD ','Wilga Park B Power Station');
insert into stationdata values('STHBKTEC',1,'Fossil','Diesel','Combustion','Compression Reciprocating Engine','Secure Energy Pty Ltd','Southbank Institute Of Technology Unit 1 Plant');
insert into stationdata values('SNOWTWN1',99,'Wind','Wind','Renewable','Wind - Onshore','Snowtown Wind Farm Pty Ltd','Snowtown Wind Farm Units 1 And 47');
insert into stationdata values('SNOWSTH1',126,'Wind','Wind','Renewable','Wind - Onshore','Snowtown Wind Farm Stage 2 Pty ltd ','Snowtown South Wind Farm');
insert into stationdata values('SNOWNTH1',144,'Wind','Wind','Renewable','Wind - Onshore','Snowtown Wind Farm Stage 2 Pty ltd ','Snowtown Wind Farm Stage 2 North');
insert into stationdata values('BLOWERNG',70,'Hydro','Water','Renewable','Hydro - Gravity','Snowy Hydro Limited','Blowering Power Station');
insert into stationdata values('CG1',181,'Fossil','Natural Gas','Combustion','Open Cycle Gas turbines (OCGT)','Snowy Hydro Limited','Colongra Power Station');
insert into stationdata values('CG2',181,'Fossil','Natural Gas','Combustion','Open Cycle Gas turbines (OCGT)','Snowy Hydro Limited','Colongra Power Station');
insert into stationdata values('CG3',181,'Fossil','Natural Gas','Combustion','Open Cycle Gas turbines (OCGT)','Snowy Hydro Limited','Colongra Power Station');
insert into stationdata values('CG4',181,'Fossil','Natural Gas','Combustion','Open Cycle Gas turbines (OCGT)','Snowy Hydro Limited','Colongra Power Station');
insert into stationdata values('GUTHEGA',60,'Hydro','Water','Renewable','Hydro - Gravity','Snowy Hydro Limited','Guthega Power Station');
insert into stationdata values('GUTHEGA',,'Hydro','Water','Renewable','Hydro - Gravity','Snowy Hydro Limited','Guthega Power Station');
insert into stationdata values('JNDABNE1',1.1,'Hydro','Water','Renewable','Hydro - Gravity','Snowy Hydro Limited','Jindabyne Small Hydro Power Station ');
insert into stationdata values('JOUNAMA1',14,'Hydro','Water','Renewable','Hydro - Gravity','Snowy Hydro Limited','Jounama Small Hydro Power Station');
insert into stationdata values('LNGS1',156,'Fossil','Natural Gas','Combustion','Open Cycle Gas turbines (OCGT)','Snowy Hydro Limited','Laverton North Power Station');
insert into stationdata values('LNGS2',156,'Fossil','Natural Gas','Combustion','Open Cycle Gas turbines (OCGT)','Snowy Hydro Limited','Laverton North Power Station');
insert into stationdata values('MURRAY',1500,'Hydro','Water','Renewable','Hydro - Gravity','Snowy Hydro Limited','Murray 1 Power Station');
insert into stationdata values('MURRAY',,'Hydro','Water','Renewable','Hydro - Gravity','Snowy Hydro Limited','Murray 2 Power Station');
insert into stationdata values('UPPTUMUT',616,'Hydro','Water','Renewable','Hydro - Gravity','Snowy Hydro Limited','Tumut 1 Power Station');
insert into stationdata values('UPPTUMUT',,'Hydro','Water','Renewable','Hydro - Gravity','Snowy Hydro Limited','Tumut 2 Power Station');
insert into stationdata values('TUMUT3',1500,'Hydro','Water','Renewable','Hydro - Gravity','Snowy Hydro Limited','Tumut 3 Power Station');
insert into stationdata values('VPGS1',50,'Fossil','Natural Gas','Combustion','Open Cycle Gas turbines (OCGT)','Snowy Hydro Limited','Valley Power Peaking Facility');
insert into stationdata values('VPGS2',50,'Fossil','Natural Gas','Combustion','Open Cycle Gas turbines (OCGT)','Snowy Hydro Limited','Valley Power Peaking Facility');
insert into stationdata values('VPGS3',50,'Fossil','Natural Gas','Combustion','Open Cycle Gas turbines (OCGT)','Snowy Hydro Limited','Valley Power Peaking Facility');
insert into stationdata values('VPGS4',50,'Fossil','Natural Gas','Combustion','Open Cycle Gas turbines (OCGT)','Snowy Hydro Limited','Valley Power Peaking Facility');
insert into stationdata values('VPGS5',50,'Fossil','Natural Gas','Combustion','Open Cycle Gas turbines (OCGT)','Snowy Hydro Limited','Valley Power Peaking Facility');
insert into stationdata values('VPGS6',50,'Fossil','Natural Gas','Combustion','Open Cycle Gas turbines (OCGT)','Snowy Hydro Limited','Valley Power Peaking Facility');
insert into stationdata values('BARRON-1',30,'Hydro','Water','Renewable','Run of River','Stanwell Corporation Limited','Barron Gorge Power Station');
insert into stationdata values('BARRON-2',30,'Hydro','Water','Renewable','Run of River','Stanwell Corporation Limited','Barron Gorge Power Station');
insert into stationdata values('KAREEYA1',21,'Hydro','Water','Renewable','Run of River','Stanwell Corporation Limited','Kareeya Power Station');
insert into stationdata values('KAREEYA2',21,'Hydro','Water','Renewable','Run of River','Stanwell Corporation Limited','Kareeya Power Station');
insert into stationdata values('KAREEYA3',18,'Hydro','Water','Renewable','Run of River','Stanwell Corporation Limited','Kareeya Power Station');
insert into stationdata values('KAREEYA4',21,'Hydro','Water','Renewable','Run of River','Stanwell Corporation Limited','Kareeya Power Station');
insert into stationdata values('KAREEYA5',7,'Hydro','Water','Renewable','Run of River','Stanwell Corporation Limited','Kareeya Power Station');
insert into stationdata values('MACKAYGT',30,'Fossil','Diesel','Combustion','Open Cycle Gas turbines (OCGT)','Stanwell Corporation Limited','Mackay Gas Turbine');
insert into stationdata values('STAN-1',365,'Fossil','Black Coal','Combustion','Steam Sub-Critical','Stanwell Corporation Limited','Stanwell Power Station');
insert into stationdata values('STAN-2',365,'Fossil','Black Coal','Combustion','Steam Sub-Critical','Stanwell Corporation Limited','Stanwell Power Station');
insert into stationdata values('STAN-3',365,'Fossil','Black Coal','Combustion','Steam Sub-Critical','Stanwell Corporation Limited','Stanwell Power Station');
insert into stationdata values('STAN-4',365,'Fossil','Black Coal','Combustion','Steam Sub-Critical','Stanwell Corporation Limited','Stanwell Power Station');
insert into stationdata values('SWAN_E',385,'Fossil','Natural Gas','Combustion','Combined Cycle Gas Turbine (CCGT)','Stanwell Corporation Limited','Swanbank E Gas Turbine');
insert into stationdata values('TNPS1',443,'Fossil','Black Coal','Combustion','Steam Super Critical','Stanwell Corporation Limited','Tarong North Power Station');
insert into stationdata values('-',15,'Fossil','Natural Gas','Combustion','Open Cycle Gas turbines (OCGT)','Stanwell Corporation Limited','Tarong Power Station');
insert into stationdata values('TARONG#1',350,'Fossil','Black Coal','Combustion','Steam Sub-Critical','Stanwell Corporation Limited','Tarong Power Station');
insert into stationdata values('TARONG#2',350,'Fossil','Black Coal','Combustion','Steam Sub-Critical','Stanwell Corporation Limited','Tarong Power Station');
insert into stationdata values('TARONG#3',350,'Fossil','Black Coal','Combustion','Steam Sub-Critical','Stanwell Corporation Limited','Tarong Power Station');
insert into stationdata values('TARONG#4',350,'Fossil','Black Coal','Combustion','Steam Sub-Critical','Stanwell Corporation Limited','Tarong Power Station');
insert into stationdata values('WIVENSH',4.7,'Hydro','Water','Renewable','Run of River','Stanwell Corporation Limited','Wivenhoe Small Hydro');
insert into stationdata values('STARHLWF',34.5,'Wind','Wind','Renewable','Wind - Onshore','Starfish Hill Wind Farm Pty Ltd ','Starfish Hill Wind Farm');
insert into stationdata values('DRYCGT1',52,'Fossil','Natural Gas','Combustion','Open Cycle Gas turbines (OCGT)','Synergen Power Pty Limited','Dry Creek Gas Turbine Station');
insert into stationdata values('DRYCGT2',52,'Fossil','Natural Gas','Combustion','Open Cycle Gas turbines (OCGT)','Synergen Power Pty Limited','Dry Creek Gas Turbine Station');
insert into stationdata values('DRYCGT3',52,'Fossil','Natural Gas','Combustion','Open Cycle Gas turbines (OCGT)','Synergen Power Pty Limited','Dry Creek Gas Turbine Station');
insert into stationdata values('MINTARO',90,'Fossil','Natural Gas','Combustion','Open Cycle Gas turbines (OCGT)','Synergen Power Pty Limited','Mintaro Gas Turbine Station');
insert into stationdata values('POR01',50,'Fossil','Diesel','Combustion','Open Cycle Gas turbines (OCGT)','Synergen Power Pty Limited','Port Lincoln Gas Turbine');
insert into stationdata values('POR03',23.5,'Fossil','Diesel','Combustion','Open Cycle Gas turbines (OCGT)','Synergen Power Pty Limited','Port Lincoln Gas Turbine');
insert into stationdata values('SNUG1',63,'Fossil','Diesel','Combustion','Open Cycle Gas turbines (OCGT)','Synergen Power Pty Limited','Snuggery Power Station');
insert into stationdata values('TARALGA1',106.8,'Wind','Wind','Renewable','Wind - Onshore','Taralga Wind Farm Nominees No 2 Pty Ltd (ATF Taralga Wind Farm Operating Trust)','Taralga Wind Farm');
insert into stationdata values('MIDLDPS1',6,'Hydro','Hydro','Renewable','Hydro - Gravity','Tasmanian Irrigation Pty Ltd','Midlands Power Station');
insert into stationdata values('TOORAWF',21,'Wind','Wind','Renewable','Wind - Onshore','Toora Wind Farm Pty Ltd ','Toora Wind Farm');
insert into stationdata values('TITREE',2,'Renewable/ Biomass / Waste','Landfill Methane / Landfill Gas','Combustion','Compression Reciprocating Engine','Veolia Environmental Services (Australia) Pty Ltd','Veolia Ti Tree Bio Reactor');
insert into stationdata values('WATERLWF',111,'Wind','Wind','Renewable','Wind - Onshore','Waterloo Wind Farm Pty Ltd','Waterloo Wind Farm');
insert into stationdata values('INVICTA',50,'Renewable/ Biomass / Waste','Bagasse','Combustion','Steam Sub-Critical','Wilmar Sugar Pty Ltd','Invicta Sugar Mill');
insert into stationdata values('INVICTA',50,'Renewable/ Biomass / Waste','Bagasse','Combustion','Steam Sub-Critical','Wilmar Sugar Pty Ltd','Invicta Sugar Mill');
insert into stationdata values('INVICTA',50,'Renewable/ Biomass / Waste','Bagasse','Combustion','Steam Sub-Critical','Wilmar Sugar Pty Ltd','Invicta Sugar Mill');
insert into stationdata values('-',5,'Renewable/ Biomass / Waste','Bagasse','Combustion','Steam - Super heated','Wilmar Sugar Pty Ltd','Victoria Mill ');
insert into stationdata values('-',19,'Renewable/ Biomass / Waste','Bagasse','Combustion','Steam - Super heated','Wilmar Sugar Pty Ltd','Victoria Mill ');
insert into stationdata values('WHILL1',12,'Wind','Wind','Renewable','Wind - Onshore','Windy Hill Wind Farm Pty Ltd ','Windy Hill Wind Farm');
insert into stationdata values('WOODLWN1',48,'Wind','Wind','Renewable','Wind - Onshore','Woodlawn Wind Pty Ltd','Woodlawn Wind Farm');

